name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Test
      run: |
        cd go
        go test -v ./...
    
    - name: Build
      run: |
        cd go
        go build -v ./...

  rust:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Test
      run: |
        cd rust
        cargo test --all-features
    
    - name: Build
      run: |
        cd rust
        cargo build --release

  conformance:
    name: Conformance Tests
    needs: [go, rust]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build servers
      run: |
        cd go && go build -o ../hyperserve-go ./cmd/hyperserve
        cd ../rust && cargo build --release --bin hyperserve
        cp target/release/hyperserve ../hyperserve-rust
    
    - name: Run conformance tests
      run: |
        cd tests
        # TODO: Add conformance test runner